### ISSUE TITLE
Cut release for GHC 8.10.1

### ISSUE THREAD

**Issue by bgamari** [ekmett/exceptions#79]
GHC 8.10.1 will ship with `exceptions` based on ed98b644973430e26b93a4d12f75ad963c7afd20. It would be great to cut a release from this commit.

**Comment by RyanGlScott** [comment]
What do you mean by "from this commit [ed98b64]"? Do you mean uploading that exact commit to Hackage? I ask since `exceptions` HEAD already has changes beyond that commit (in the form of commit 0a1f9ff0f407da360fc9405a07d5d06d28e6c077), and I usually make some extra commits to update the `CHANGELOG`/`.cabal` file just before cutting a new release.

**Comment by bgamari** [comment]
I should have been clearer; I mean "cut a release that includes that commit". Of course, this may include (ideally small) additional commits and I would fully expect that `changelog`/`.cabal` wrangling is necessary as part of the release process.

**Comment by RyanGlScott** [comment]
Good to know, thanks for the clarification.

I have uploaded [`exceptions-0.10.4`](http://hackage.haskell.org/package/exceptions-0.10.4) to Hackage.
